version: '2'

services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    env_file: ./mysql.env
    volumes: 
        - ./mysql:/var/lib/mysql
    ports:
     - 3306:3306


  europa:
    image: distelli/europa:latest
    env_file: ./europa.env
    volumes: 
        - ./europa:/europa/repo
    ports:
     - 5000:80