apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-services
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: dashboard.192.168.99.100.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80

#   - host: europa.192.168.99.100.xip.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: europa
#           servicePort: 80

  - host: grafana.192.168.99.100.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana
          servicePort: 80