apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-services
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: europa.192.168.42.134.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: europa
          servicePort: 80