apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: europa
        - name: MYSQL_PASSWORD
          value: europa
        - name: MYSQL_USER
          value: europa
        - name: MYSQL_DATABASE
          value: europa
        - name: MYSQL_ROOT_HOST
          value: mysql
        ports:
        - containerPort: 3306
          name: mysql
    #     volumeMounts:
    #     - name: mysql-persistent-storage
    #       mountPath: /var/lib/mysql
    #   volumes:
    #   - name: mysql-persistent-storage
    #     persistentVolumeClaim:
    #       claimName: myclaim
