#!/bin/sh


mkdir ~/node-app
cd ~/node-app
git init
git remote add origin https://github.com/KMurphs/Tutorials.git
git pull origin master
npm install — production
pm2 start node-app/Tutorials/Jenkins_NodeJS/index.js
pm2 restart all
EOF