apiVersion: v1
kind: Service
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-kenzan
    tier: hello-kenzan
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-kenzan
        tier: hello-kenzan
    spec:
      containers:
      - image: __IMAGE__
        name: hello-kenzan
        ports:
        - containerPort: 80
          name: hello-kenzan
          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kenzan
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: hello-kenzan.192.168.42.61.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-kenzan
          servicePort: 80