FROM redis


# RUN ls /etc
# COPY /etc/redis/redis.conf /etc/redis/redis.default.conf
# CMD [ "redis-server", "/etc/redis/redis.conf" ]
CMD [ "redis-server"]


# docker build -t redisstore -f Dockerfile .
# docker run -p 6379:6379 --name redisstore redisstore