server:
  port: 8080
  address: 0.0.0.0
redis:
  enabled: true
  connection: redis://redis:6379
  scheduler: default
  parallelism: -1

cassandra:
  enabled: false
  embedded: false
  host: cassandra
  keyspace: 'front50'
  cluster: 'Test Cluster'
  name: default

spinnaker:

  redis:
    enabled: true
    connection: redis://redis:6379
    scheduler: default
    parallelism: -1

  cassandra:
    enabled: false
    embedded: false
    cluster: 'Test Cluster'
    host: cassandra
    keyspace: 'front50'
    name: default


swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*