apiVersion: v1
kind: Service
metadata:
  name: monitor-scale
  labels:
    app: monitor-scale
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: monitor-scale
    tier: monitor-scale
  type: NodePort

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-scale
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: puzzle-scaler
rules:
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - deployments/scale
  resourceNames:
  - "puzzle"
  verbs:
  - update
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-scale-puzzle-scaler
  namespace: default
roleRef:
  kind: Role
  name: puzzle-scaler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: monitor-scale
  namespace: default

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-scale
  labels:
    app: monitor-scale
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monitor-scale
        tier: monitor-scale
    spec:
      serviceAccountName: monitor-scale
      containers:
      - image: 127.0.0.1:30400/monitor-scale:$BUILD_TAG
        name: monitor-scale
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: monitor-scale
      - image: zappi/kubectl:latest
        name: kubectl-api
        args: ["proxy","-p","2345"]
        ports:
        - containerPort: 2345
          name: kubectl-api          

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: monitor-scale
 annotations:
  ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: monitor-scale
    servicePort: 3001
  rules:
  - host: monitor-scale.192.168.99.100.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: monitor-scale
          servicePort: 3001
