apiVersion: v1
kind: Service
metadata:
  name: kr8sswordz
  labels:
    app: kr8sswordz
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: kr8sswordz
    tier: kr8sswordz
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kr8sswordz
  labels:
    app: kr8sswordz
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kr8sswordz
        tier: kr8sswordz
    spec:
      containers:
      - image: 127.0.0.1:30912/kr8sswordz:1.0.0
        name: kr8sswordz
        ports:
        - containerPort: 3000
          name: kr8sswordz

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: kr8sswordz
 annotations:
  ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: kr8sswordz
    servicePort: 80
  rules:
  - host: kr8sswordz.MINIKUBEIP.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kr8sswordz
          servicePort: 80